# Generated by Django 4.2.30 on 2026-09-07 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='Fruitful Brethren Ministry International', max_length=200)),
                ('short_name', models.CharField(default='F.B.M.I.', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('primary_color', models.CharField(default='#6794A6', max_length=7)),
                ('secondary_color', models.CharField(default='#546280', max_length=7)),
                ('accent_color', models.CharField(default='#BF2D30', max_length=7)),
                ('gold_color', models.CharField(default='#BAA883', max_length=7)),
                ('service_times', models.TextField(blank=True, help_text='One per line')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church Setting',
                'verbose_name_plural': 'Church Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
